// <auto-generated />
using Iantech.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Iantech.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190101145922_CompetidorModel")]
    partial class CompetidorModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Iantech.Models.CompetidorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo");

                    b.Property<string>("Direccion");

                    b.Property<string>("Lat");

                    b.Property<string>("Long");

                    b.Property<int>("Marca");

                    b.Property<int>("Marcador");

                    b.Property<string>("Nombre");

                    b.Property<string>("NombreCoorporativo");

                    b.Property<int>("Observar");

                    b.Property<int>("ZonaPrecios");

                    b.HasKey("Id");

                    b.ToTable("Competidores");
                });
#pragma warning restore 612, 618
        }
    }
}
